export const PERMISSIONS = {
    // --- CADASTROS ---
    PRODUTO_VISUALIZAR: 'PRODUTO_VISUALIZAR',
    PRODUTO_GERENCIAR: ['PRODUTO_CRIAR', 'PRODUTO_EDITAR', 'PRODUTO_EXCLUIR'],

    PARCEIRO_VISUALIZAR: 'PARCEIRO_VISUALIZAR',
    PARCEIRO_GERENCIAR: ['PARCEIRO_CRIAR', 'PARCEIRO_EDITAR', 'PARCEIRO_EXCLUIR'],

    LOCALIZACAO_VISUALIZAR: 'LOCALIZACAO_VISUALIZAR',
    LOCALIZACAO_GERENCIAR: 'LOCALIZACAO_GERENCIAR',

    // --- OPERAÇÃO ---
    RECEBIMENTO_VISUALIZAR: 'RECEBIMENTO_VISUALIZAR',
    RECEBIMENTO_OPERAR: ['RECEBIMENTO_CONFERIR', 'RECEBIMENTO_FINALIZAR'],

    ESTOQUE_VISUALIZAR: 'ESTOQUE_VISUALIZAR',
    ESTOQUE_OPERAR: ['ESTOQUE_MOVIMENTAR', 'ESTOQUE_ARMAZENAR'],
    ESTOQUE_GERENCIAR: 'ESTOQUE_GERENCIAR',

    EXPEDICAO_VISUALIZAR: 'PEDIDO_VISUALIZAR',
    EXPEDICAO_OPERAR: ['EXPEDICAO_SEPARAR', 'EXPEDICAO_CONFERIR', 'EXPEDICAO_DESPACHAR'],

    // --- NOVOS MÓDULOS ---
    INVENTARIO_VER: ['INVENTARIO_CRIAR', 'INVENTARIO_APROVAR', 'INVENTARIO_CONTAR'],
    INVENTARIO_GERENCIAR: ['INVENTARIO_CRIAR', 'INVENTARIO_APROVAR'],

    FATURAMENTO_VER: 'FATURAMENTO_VISUALIZAR',
    FATURAMENTO_OPERAR: 'FATURAMENTO_APONTAR',

    // --- SISTEMA & ADMIN ---
    CONFIG_SISTEMA: 'CONFIG_SISTEMA', // Agentes de Impressão
    CONFIG_EMPRESA: 'CONFIG_GERENCIAR', // Dados do Tenant

    USUARIO_GERENCIAR: ['USUARIO_CRIAR', 'USUARIO_EDITAR', 'USUARIO_EXCLUIR', 'USUARIO_LISTAR'],
    PERFIL_GERENCIAR: 'PERFIL_GERENCIAR',
    AUDITORIA_VER: 'AUDITORIA_VISUALIZAR'
};